### ISSUE TITLE
dbt-core 1.5.x support

### ISSUE THREAD

**Issue by ciklista** [Dashlane/dbt-invoke#34]
Things I found so far that need to be updated to support `dbt-core` 1.5.0: (I was hoping that https://github.com/Dashlane/dbt-invoke/pull/32 would be enough, but it wasn't :flushed:)

- [ ] the log output of `dbt --log-format json ls --output json` has changed compared to `dbt-core` 1.4.x which causes parsing of the result to fail. That should be pretty easy to fix. 
- [ ] Are there any other log output changes that need taken care of?
- [ ] `dbt-sqlite` needs to support `dbt-core` 1.5.0. Currently it will not run on 1.5.0 which will cause `dbt-invoke` tests to fail. An issue has been opened on the `dbt-sqllite` repo (https://github.com/codeforkjeff/dbt-sqlite/issues/43)
```
17:59:30  Traceback (most recent call last):
  File "/Users/.../code/dbt-invoke/venv_test/lib/python3.11/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/../code/dbt-invoke/venv_test/lib/python3.11/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/../code/dbt-invoke/venv_test/lib/python3.11/site-packages/dbt/cli/requires.py", line 142, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/../code/dbt-invoke/venv_test/lib/python3.11/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/../code/dbt-invoke/venv_test/lib/python3.11/site-packages/dbt/cli/requires.py", line 203, in wrapper
    config.credentials.hashed_unique_field()
  File "/Users/.../code/dbt-invoke/venv_test/lib/python3.11/site-packages/dbt/contracts/connection.py", line 144, in hashed_unique_field
    return md5(self.unique_field)
               ^^^^^^^^^^^^^^^^^
  File "/Users/jannitschke/code/dbt-invoke/venv_test/lib/python3.11/site-packages/dbt/adapters/sqlite/connections.py", line 40, in unique_field
    return self.host
           ^^^^^^^^^
AttributeError: 'SQLiteCredentials' object has no attribute 'host'
```

**Comment by robastel** [comment]
There doesn't appear to have been movement yet on dbt-sqlite supporting dbt-core 1.5. An alternative option could be to switch to [dbt-duckdb](https://github.com/jwills/dbt-duckdb).

Another change in dbt-core 1.5.0 that led to problems with dbt-invoke is described by https://github.com/dbt-labs/dbt-core/issues/7465. It appears this will be fixed in dbt-core 1.5.2.

**Comment by alexnikitchuk** [comment]
Is there any timeline to fix the issues?
